export const REQUEST_BOOKS = 'REQUEST_BOOKS'
export const GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE'
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS'

export const REQUEST_LOCATIONS = 'REQUEST_LOCATIONS'
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE'
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS'

export const REQUEST_JOINS = 'REQUEST_JOINS'
export const GET_JOINS_FAILURE = 'GET_JOINS_FAILURE'
export const GET_JOINS_SUCCESS = 'GET_JOINS_SUCCESS'

